MilenaEmbroidery.WebApp/Areas/Shop/Controllers/OrderListController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MilenaEmbroidery.DTOs.Shop;
using MilenaEmbroidery.IServices.Shop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MilenaEmbroidery.WebApp.Areas.Admin.Controllers
{
    [Area("shop")]
    public class OrderListController : Controller
    {
        private readonly IOrderListService _orderListService;
        public OrderListController(IOrderListService orderListService)
        {
            _orderListService = orderListService;
        }

        public async Task<IActionResult> BasketForm()
        {
            IEnumerable<OrderListDTO> orderLists = Enumerable.Empty<OrderListDTO>();

            try
            {
                int? orderId = HttpContext.Session.GetInt32("OrderId");

                if (orderId == null)
                    throw new Exception("Order ID not found");

                orderLists = await _orderListService.GetByOrderId((int)orderId);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return View(orderLists.ToList());
        }

        public async Task<IActionResult> Update(IList<OrderListDTO> orderLists)
        {
            try
            {
                foreach (var item in orderLists)
                {
                    if (item.Quantity == 0)
                    {
                        bool check = await _orderListService.CheckIfExists(item.Id);

                        if (!check)
                            throw new Exception("Order list not exist.");

                        await _orderListService.Delete(item.Id);
                    }
                    else
                        await _orderListService.Update(item);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            bool check = false;

            try
            {
                check = await _orderListService.CheckIfExists(id);

                if (!check)
                    throw new Exception("Order list not exist.");

                await _orderListService.Delete(id);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return RedirectToAction("BasketForm");
        }
    }
}

MilenaEmbroidery.WebApp/Areas/Shop/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MilenaEmbroidery.DTOs.General;
using MilenaEmbroidery.DTOs.Shop;
using MilenaEmbroidery.IServices.General;
using MilenaEmbroidery.IServices.Shop;
using System;
using System.Threading.Tasks;

namespace MilenaEmbroidery.WebApp.Areas.Shop.Controllers
{
    [Area("shop")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IOrderService _orderService;

        public object Session { get; private set; }

        public UserController(IUserService userService, IOrderService orderService)
        {
            _userService = userService;
            _orderService = orderService;
        }

        public IActionResult LoginForm()
        {
            return View();
        }

        public async Task<IActionResult> UserForm()
        {
            UserDTO user = null;

            try
            {
                int? userId = HttpContext.Session.GetInt32("UserId");

                if (userId == null)
                    throw new Exception("UserId is null! Cannot get data.");

                user = await _userService.Get((int)userId);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return View(user);
        }

        public async Task<IActionResult> EditForm()
        {
            UserDTO user = null;

            try
            {
                int? userId = HttpContext.Session.GetInt32("UserId");

                if (userId == null)
                    throw new Exception("UserId is null! Cannot get data.");

                user = await _userService.Get((int)userId);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return View(user);
        }

        public async Task<IActionResult> Update(UserDTO user)
        {
            try
            {
                await _userService.Update(user);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return RedirectToAction("UserForm");
        }

        public async Task<IActionResult> Login(UserDTO user)
        {
            UserDTO loggedUser = null;
            OrderDTO order = null;

            try
            {
                loggedUser = await _userService.Login(user.FirstName, user.LastName);

                if (loggedUser is NullUserDTO)
                    throw new Exception("Login Failed. Data not found.");

                order = await _orderService.Get(loggedUser.Id);

                if (order.Id > 0)
                    HttpContext.Session.SetInt32("OrderId", order.Id);

                HttpContext.Session.SetInt32("UserId", loggedUser.Id);
                HttpContext.Session.SetString("Login", loggedUser.FirstName);
                HttpContext.Session.SetString("IsAdmin", loggedUser.IsAdmin.ToString());
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            try
            {
                HttpContext.Session.Clear();
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.GetBaseException().Message);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

MilenaEmbroidery.WebApp/Views/Shared/_Layout.cshtml
@{ 
    var login = Context.Session.GetString("Login");
    var basket = Context.Session.GetInt32("OrderId");
    var isAdmin = Context.Session.GetString("IsAdmin");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MilenaEmbroidery Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Shop" asp-controller="Home" asp-action="Index">MilenaEmbroidery Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Shop" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Shop" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (isAdmin == "True")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (basket != null)
                {
                    <a class="text-dark" asp-area="Shop" asp-controller="OrderList" asp-action="BasketForm">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-basket2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M4 10a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 1 1 2 0v2a1 1 0 0 1-2 0v-2z" />
                            <path fill-rule="evenodd" d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-.623l-1.844 6.456a.75.75 0 0 1-.722.544H3.69a.75.75 0 0 1-.722-.544L1.123 8H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.163 8l1.714 6h8.246l1.714-6H2.163z" />
                        </svg>
                    </a>
                }
                @if (login != null)
                {
                    <a class="nav-link text-dark" asp-area="Shop" asp-controller="User" asp-action="UserForm">@login</a>
                    <a class="nav-link text-dark" asp-area="Shop" asp-controller="User" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a class="nav-link text-dark" asp-area="Shop" asp-controller="User" asp-action="LoginForm">Login</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MilenaEmbroidery Shop - <a asp-area="Shop" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>